# Generated by Django 5.1.2 on 2024-10-31 12:08

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Endereco',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rua', models.CharField(max_length=100)),
                ('numero', models.CharField(max_length=100)),
                ('complemento', models.CharField(blank=True, max_length=100)),
                ('cidade', models.CharField(max_length=100)),
                ('estado', models.CharField(max_length=100)),
                ('cep', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='ExperienciaProfissional',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cargo', models.CharField(max_length=100)),
                ('empresa', models.CharField(max_length=100)),
                ('descricao', models.TextField()),
                ('periodo_inicio', models.DateField()),
                ('periodo_fim', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='FormacaoAcademica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('instituicao', models.CharField(max_length=100)),
                ('curso', models.CharField(max_length=100)),
                ('periodo_inicio', models.DateField()),
                ('periodo_fim', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Candidato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('telefone', models.CharField(max_length=15, validators=[django.core.validators.RegexValidator(message='O telefone deve ter 9 a 15 dígitos.', regex='^\\+?1?\\d{9,15}$')])),
                ('cargo', models.CharField(max_length=100)),
                ('data_nascimento', models.DateField()),
                ('nacionalidade', models.CharField(max_length=50)),
                ('estado_civil', models.CharField(max_length=20)),
                ('skills', models.TextField(blank=True)),
                ('languages', models.TextField(blank=True)),
                ('cover_letter', models.TextField(blank=True)),
                ('endereco', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='candidatos.endereco')),
            ],
        ),
        migrations.CreateModel(
            name='CandidatoExperienciaProfissional',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('candidato', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='candidatos.candidato')),
                ('experiencia_profissional', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='candidatos.experienciaprofissional')),
            ],
        ),
        migrations.AddField(
            model_name='candidato',
            name='experiencias_profissionais',
            field=models.ManyToManyField(blank=True, through='candidatos.CandidatoExperienciaProfissional', to='candidatos.experienciaprofissional'),
        ),
        migrations.CreateModel(
            name='CandidatoFormacaoAcademica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('candidato', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='candidatos.candidato')),
                ('formacao_academica', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='candidatos.formacaoacademica')),
            ],
        ),
        migrations.AddField(
            model_name='candidato',
            name='formacoes_academicas',
            field=models.ManyToManyField(blank=True, through='candidatos.CandidatoFormacaoAcademica', to='candidatos.formacaoacademica'),
        ),
    ]
